import type { WorkOrder } from "./types";

export const STORAGE_KEY = "ski-tuning-confirmed-v1";

export function seedOrders(): WorkOrder[] {
  return [
    {
      id: "ORD-106",
      board: "Burton 156",
      length: 156,
      boardType: "全地域",
      sideEdge: 88,
      baseEdge: 1,
      waxType: "低温蜡",
      baseDamage: "无明显损伤",
      tasks: ["wax", "edge"],
      promise: 60,
      priority: "normal",
      status: "promised",
      slot: { wax: { start: 0, end: 20 }, edge: { start: 0, end: 15 } },
      createdAt: 1,
    },
    {
      id: "ORD-112",
      board: "Head 竞速165",
      length: 165,
      boardType: "竞速板",
      sideEdge: 89,
      baseEdge: 1.5,
      waxType: "高温蜡",
      baseDamage: "底板划痕12cm，待补P-Tex",
      tasks: ["base", "edge", "wax"],
      promise: 90,
      priority: "normal",
      status: "working",
      slot: {
        base: { start: 0, end: 45 },
        edge: { start: 45, end: 60 },
        wax: { start: 45, end: 65 },
      },
      createdAt: 2,
    },
    {
      id: "ORD-118",
      board: "Jones 粉雪158",
      length: 158,
      boardType: "粉雪板",
      sideEdge: 87,
      baseEdge: 0.5,
      waxType: "低温蜡",
      baseDamage: "客户偏好弱咬雪",
      tasks: ["wax", "edge"],
      promise: 120,
      priority: "normal",
      status: "promised",
      slot: { wax: { start: 0, end: 20 }, edge: { start: 0, end: 15 } },
      createdAt: 3,
    },
    {
      id: "ORD-120",
      board: "Salomon 全地域160",
      length: 160,
      boardType: "全地域",
      sideEdge: 88,
      baseEdge: 1,
      waxType: "低温蜡",
      baseDamage: "底板划痕5cm",
      tasks: ["base", "wax"],
      promise: 140,
      priority: "normal",
      status: "pending",
      createdAt: 4,
    },
    {
      id: "ORD-122",
      board: "Lib Tech 公园152",
      length: 152,
      boardType: "公园板",
      sideEdge: 88,
      baseEdge: 2,
      waxType: "高温蜡",
      baseDamage: "无明显损伤",
      tasks: ["edge", "wax"],
      promise: 200,
      priority: "normal",
      status: "pending",
      createdAt: 5,
    },
  ];
}
